name: Build Spotifyd for Raspberry Pi (Cross Tool)

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

env:
  TARGET: arm-unknown-linux-gnueabihf

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout spotifyd repo
      uses: actions/checkout@v4
    
    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@stable
      with:
        targets: ${{ env.TARGET }}
    
    - name: Install cross
      run: cargo install cross --git https://github.com/cross-rs/cross
    
    - name: Update Cargo.toml to use latest librespot dev
      run: |
        # Backup original files
        cp Cargo.toml Cargo.toml.backup
        
        # Remove Cargo.lock to allow fresh dependency resolution
        rm -f Cargo.lock
        
        # Update librespot dependencies to use dev branch
        echo "Original Cargo.toml librespot dependencies:"
        grep -n "librespot" Cargo.toml || true
        
        # Simple replacement to use git dev branch
        sed -i 's/librespot = { version = "[^"]*"/librespot = { git = "https:\/\/github.com\/librespot-org\/librespot.git", branch = "dev"/' Cargo.toml
        
        echo ""
        echo "Updated Cargo.toml:"
        grep -n "librespot" Cargo.toml || true
    
    - name: Cache cross dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cross-${{ env.TARGET }}-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cross-${{ env.TARGET }}-
          ${{ runner.os }}-cross-
    
    - name: Build spotifyd with cross
      run: |
        cross build \
          --target ${{ env.TARGET }} \
          --release \
          --no-default-features \
          --features "alsa_backend,dbus_mpris"
    
    - name: Create build info
      run: |
        echo "Build completed at: $(date)" > build_info.txt
        echo "Target: ${{ env.TARGET }}" >> build_info.txt
        echo "Features: alsa_backend,dbus_mpris" >> build_info.txt
        echo "Librespot: Latest dev branch (fixes Aug 2025 Spotify API issues)" >> build_info.txt
        echo "Cross tool version: $(cross --version)" >> build_info.txt
        echo "Binary size: $(ls -lh target/${{ env.TARGET }}/release/spotifyd | awk '{print $5}')" >> build_info.txt
        echo "SHA256: $(sha256sum target/${{ env.TARGET }}/release/spotifyd | awk '{print $1}')" >> build_info.txt
    
    - name: Upload spotifyd binary
      uses: actions/upload-artifact@v4
      with:
        name: spotifyd-rpi-zero-w2-cross-${{ github.sha }}
        path: |
          target/${{ env.TARGET }}/release/spotifyd
          build_info.txt
        retention-days: 30
    
    - name: Upload to release (if tag)
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: |
          target/${{ env.TARGET }}/release/spotifyd
          build_info.txt
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
