name: build-armv7-spotifyd
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    env:
      TARGET: armv7-unknown-linux-gnueabihf
      CARGO_TERM_COLOR: always
      DEBIAN_FRONTEND: noninteractive

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Add Cargo patches for librespot dev
        run: |
          mkdir -p .cargo
          cat > .cargo/config.toml <<'EOF'
          [patch.crates-io]
          librespot               = { git = "https://github.com/librespot-org/librespot", branch = "dev" }
          librespot-core          = { git = "https://github.com/librespot-org/librespot", branch = "dev" }
          librespot-playback      = { git = "https://github.com/librespot-org/librespot", branch = "dev" }
          librespot-protocol      = { git = "https://github.com/librespot-org/librespot", branch = "dev" }
          librespot-metadata      = { git = "https://github.com/librespot-org/librespot", branch = "dev" }
          librespot-audio         = { git = "https://github.com/librespot-org/librespot", branch = "dev" }
          librespot-discovery     = { git = "https://github.com/librespot-org/librespot", branch = "dev" }
          librespot-connect       = { git = "https://github.com/librespot-org/librespot", branch = "dev" }
          EOF

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ env.TARGET }}

      # ---- KEY FIX ----
      - name: Enable armhf & point ONLY to ports.ubuntu.com
        run: |
          sudo dpkg --add-architecture armhf
          # Drop any armhf entries that may default to security.ubuntu.com
          sudo sed -i.bak '/^\s*deb .* \[.*arch=armhf.*\]/d' /etc/apt/sources.list || true
          sudo sed -i    '/^\s*deb .* armhf /d'               /etc/apt/sources.list || true
          # Add proper armhf sources
          sudo tee /etc/apt/sources.list.d/armhf.list >/dev/null <<'EOF'
          deb [arch=armhf] http://ports.ubuntu.com/ jammy main universe multiverse restricted
          deb [arch=armhf] http://ports.ubuntu.com/ jammy-updates main universe multiverse restricted
          deb [arch=armhf] http://ports.ubuntu.com/ jammy-security main universe multiverse restricted
          deb [arch=armhf] http://ports.ubuntu.com/ jammy-backports main universe multiverse restricted
          EOF
          sudo apt-get update
          # Sanity: show where armhf will be pulled from
          grep -R --line-number 'ports.ubuntu.com' /etc/apt/sources.list.d/armhf.list
          apt-cache policy | sed -n '1,120p'

      - name: Install cross deps (armhf toolchain & headers)
        run: |
          sudo apt-get install -y \
            gcc-arm-linux-gnueabihf \
            pkg-config-arm-linux-gnueabihf \
            libasound2-dev:armhf \
            libssl-dev:armhf \
            libpulse-dev:armhf \
            libdbus-1-dev:armhf

      - name: Configure cross env
        run: |
          echo "PKG_CONFIG_ALLOW_CROSS=1" >> $GITHUB_ENV
          echo "PKG_CONFIG_PATH=/usr/lib/arm-linux-gnueabihf/pkgconfig" >> $GITHUB_ENV
          echo "PKG_CONFIG_LIBDIR=/usr/lib/arm-linux-gnueabihf/pkgconfig" >> $GITHUB_ENV
          echo "CARGO_TARGET_ARMV7_UNKNOWN_LINUX_GNUEABIHF_LINKER=arm-linux-gnueabihf-gcc" >> $GITHUB_ENV
          echo "CC_armv7_unknown_linux_gnueabihf=arm-linux-gnueabihf-gcc" >> $GITHUB_ENV
          echo "RUSTFLAGS=-C codegen-units=1 -C opt-level=z" >> $GITHUB_ENV

      - name: Cargo update (apply patches)
        run: cargo update

      - name: Build (ARMv7, ALSA + MPRIS)
        run: |
          cargo build --release \
            --target $TARGET \
            --features "alsa_backend,dbus_mpris"

      - name: Show librespot sources (sanity)
        run: cargo tree --target $TARGET | grep -E 'librespot( |-)'

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: spotifyd-armv7
          path: target/${{ env.TARGET }}/release/spotifyd
