name: build-armv7-spotifyd
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    env:
      TARGET: armv7-unknown-linux-gnueabihf
      CARGO_TERM_COLOR: always
      DEBIAN_FRONTEND: noninteractive

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Force spotifyd to use librespot's dev branch (contains the track-availability fix)
      - name: Add Cargo patches for librespot dev
        run: |
          mkdir -p .cargo
          cat > .cargo/config.toml <<'EOF'
          [patch.crates-io]
          librespot               = { git = "https://github.com/librespot-org/librespot", branch = "dev" }
          librespot-core          = { git = "https://github.com/librespot-org/librespot", branch = "dev" }
          librespot-playback      = { git = "https://github.com/librespot-org/librespot", branch = "dev" }
          librespot-protocol      = { git = "https://github.com/librespot-org/librespot", branch = "dev" }
          librespot-metadata      = { git = "https://github.com/librespot-org/librespot", branch = "dev" }
          librespot-audio         = { git = "https://github.com/librespot-org/librespot", branch = "dev" }
          librespot-discovery     = { git = "https://github.com/librespot-org/librespot", branch = "dev" }
          librespot-connect       = { git = "https://github.com/librespot-org/librespot", branch = "dev" }
          EOF

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ env.TARGET }}

      # Jammy needs armhf repos from ports.ubuntu.com
      - name: Enable armhf & add ports sources
        run: |
          sudo dpkg --add-architecture armhf
          sudo tee /etc/apt/sources.list.d/armhf.list >/dev/null <<'EOF'
          deb [arch=armhf] http://ports.ubuntu.com/ jammy main universe multiverse restricted
          deb [arch=armhf] http://ports.ubuntu.com/ jammy-updates main universe multiverse restricted
          deb [arch=armhf] http://ports.ubuntu.com/ jammy-security main universe multiverse restricted
          deb [arch=armhf] http://ports.ubuntu.com/ jammy-backports main universe multiverse restricted
          EOF
          sudo apt-get update

      - name: Install cross deps (armhf toolchain & headers)
        run: |
          sudo apt-get install -y \
            gcc-arm-linux-gnueabihf \
            pkg-config-arm-linux-gnueabihf \
            libasound2-dev:armhf \
            libssl-dev:armhf \
            libpulse-dev:armhf \
            libdbus-1-dev:armhf

      - name: Configure cross env
        run: |
          echo "PKG_CONFIG_ALLOW_CROSS=1" >> $GITHUB_ENV
          echo "PKG_CONFIG_PATH=/usr/lib/arm-linux-gnueabihf/pkgconfig" >> $GITHUB_ENV
          echo "PKG_CONFIG_LIBDIR=/usr/lib/arm-linux-gnueabihf/pkgconfig" >> $GITHUB_ENV
          echo "CARGO_TARGET_ARMV7_UNKNOWN_LINUX_GNUEABIHF_LINKER=arm-linux-gnueabihf-gcc" >> $GITHUB_ENV
          echo "CC_armv7_unknown_linux_gnueabihf=arm-linux-gnueabihf-gcc" >> $GITHUB_ENV
          echo "RUSTFLAGS=-C codegen-units=1 -C opt-level=z" >> $GITHUB_ENV

      # Make sure the librespot patches actually get used
      - name: Cargo update (apply patches)
        run: cargo update

      # Optional but recommended: cache Cargo registry & target to speed retries
      - name: Cache cargo registry
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Cache target
        uses: actions/cache@v4
        with:
          path: target
          key: ${{ runner.os }}-target-${{ env.TARGET }}-${{ hashFiles('**/Cargo.lock') }}

      # Build for ARMv7 with ALSA backend (swap to pulseaudio_backend if you prefer)
      - name: Build (ARMv7)
        run: |
          cargo build --release \
            --target $TARGET \
            --features "pulseaudio_backend,dbus_mpris"

      - name: Show librespot sources (sanity)
        run: |
          cargo tree --target $TARGET | grep -E 'librespot( |-)' || true

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: spotifyd-armv7
          path: target/${{ env.TARGET }}/release/spotifyd
